#!/usr/bin/env -S dotnet fsi --

#r "nuget: Fun.Build, 1.2.0"

open System
open System.IO
open Fun.Build

let (</>) (a: string) (b: string) = Path.Combine(a, b)

let root = __SOURCE_DIRECTORY__

// --------------------------------------------------------------------------------------
// Project information, used for the generated AssemblyInfo files and the NuGet packages.
// --------------------------------------------------------------------------------------

/// The tool projects. These carry the FsLexYacc product name.
let projects = [ "FsLex"; "FsLex.Core"; "FsYacc"; "FsYacc.Core" ]

/// The runtime library, which is its own product because it ships as its own package.
let runtimeProjects = [ "FsLexYacc.Runtime" ]

let summary = "FsLex/FsYacc lexer/parser generation tools"

// --------------------------------------------------------------------------------------
// Release notes
// --------------------------------------------------------------------------------------

type Release =
    {
        /// The version exactly as written in RELEASE_NOTES.md, prerelease suffix included.
        NugetVersion: string
        /// major.minor.patch only, because an assembly version cannot carry a prerelease suffix.
        AssemblyVersion: string
        Notes: string list
    }

/// The topmost entry of RELEASE_NOTES.md, which is the one being worked towards.
///
/// An entry is a "#### <version> - <date>" heading followed by "* " bullets, and the date is
/// allowed to read "Unreleased" while the version is still in flight.
let release: Release =
    let isHeading (line: string) = line.StartsWith "####"

    let lines = File.ReadAllLines(root </> "RELEASE_NOTES.md")
    let headingIndex = Array.findIndex isHeading lines

    let version = lines.[headingIndex].TrimStart('#').Trim().Split(' ') |> Array.head

    let notes =
        lines
        |> Array.skip (headingIndex + 1)
        |> Array.takeWhile (isHeading >> not)
        |> Array.filter (String.IsNullOrWhiteSpace >> not)
        |> List.ofArray

    {
        NugetVersion = version
        AssemblyVersion = version.Split('-') |> Array.head
        Notes = notes
    }

// --------------------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------------------

/// Start a process with an explicit argument list rather than a command line.
///
/// The packaging steps pass release notes through as a single argument, and those contain
/// newlines. Handing them to a shell to be re-split would mangle them, so the arguments are
/// never joined into a string in the first place.
let exec (fileName: string) (arguments: string list) =
    async {
        let startInfo =
            Diagnostics.ProcessStartInfo(fileName, UseShellExecute = false, WorkingDirectory = root)

        for argument in arguments do
            startInfo.ArgumentList.Add argument

        use proc = Diagnostics.Process.Start startInfo
        do! proc.WaitForExitAsync() |> Async.AwaitTask
        return proc.ExitCode
    }

let cleanDirs (dirs: string list) =
    async {
        for dir in dirs do
            if Directory.Exists dir then
                Directory.Delete(dir, true)

        return 0
    }

let deleteFiles (files: string list) =
    async {
        for file in files do
            let path = root </> file

            if File.Exists path then
                File.Delete path

        return 0
    }

/// Write the AssemblyInfo.fs that every project compiles, stamped with the release version.
let writeAssemblyInfo (project: string) (product: string) =
    let version = release.AssemblyVersion

    let content =
        [
            "// Auto-Generated by build.fsx; do not edit"
            "namespace System"
            "open System.Reflection"
            ""
            $"[<assembly: AssemblyTitleAttribute(\"{project}\")>]"
            $"[<assembly: AssemblyProductAttribute(\"{product}\")>]"
            $"[<assembly: AssemblyDescriptionAttribute(\"{summary}\")>]"
            $"[<assembly: AssemblyVersionAttribute(\"{version}\")>]"
            $"[<assembly: AssemblyFileVersionAttribute(\"{version}\")>]"
            "do ()"
            ""
            "module internal AssemblyVersionInformation ="
            $"    let [<Literal>] AssemblyTitle = \"{project}\""
            $"    let [<Literal>] AssemblyProduct = \"{product}\""
            $"    let [<Literal>] AssemblyDescription = \"{summary}\""
            $"    let [<Literal>] AssemblyVersion = \"{version}\""
            $"    let [<Literal>] AssemblyFileVersion = \"{version}\""
            ""
        ]
        |> String.concat Environment.NewLine

    // A BOM, because that is what the file has always carried and the compiler reads either way.
    File.WriteAllText(root </> "src" </> project </> "AssemblyInfo.fs", content, Text.UTF8Encoding true)

let generateAssemblyInfo =
    async {
        for project in runtimeProjects do
            writeAssemblyInfo project "FsLexYacc.Runtime"

        for project in projects do
            writeAssemblyInfo project "FsLexYacc"

        return 0
    }

// --------------------------------------------------------------------------------------
// Build
// --------------------------------------------------------------------------------------

let targetFramework = "net10.0"

/// Sources fslex and fsyacc regenerate. They are deleted first so that a stale copy can never
/// be what gets compiled into the tools that are about to regenerate it.
let generatedSources =
    [
        "src/FsLex.Core/fslexlex.fs"
        "src/FsLex.Core/fslexpars.fs"
        "src/FsLex.Core/fslexpars.fsi"
        "src/FsYacc.Core/fsyacclex.fs"
        "src/FsYacc.Core/fsyaccpars.fs"
        "src/FsYacc.Core/fsyaccpars.fsi"
    ]

let generatedTestSources =
    [
        "tests/JsonLexAndYaccExample/Lexer.fs"
        "tests/JsonLexAndYaccExample/Parser.fs"
        "tests/JsonLexAndYaccExample/Parser.fsi"
        "tests/LexAndYaccMiniProject/Lexer.fs"
        "tests/LexAndYaccMiniProject/Parser.fs"
        "tests/LexAndYaccMiniProject/Parser.fsi"
    ]

let buildTools =
    async {
        let! _ = deleteFiles generatedSources

        let mutable exitCode = 0

        for project in [ "src/FsLex/fslex.fsproj"; "src/FsYacc/fsyacc.fsproj" ] do
            if exitCode = 0 then
                let! code =
                    exec "dotnet" [ "publish"; project; "-c"; "Release"; "/v:n"; "-f"; targetFramework ]

                exitCode <- code

        return exitCode
    }

/// The runtime, plus the two sample projects that exercise the freshly published tools.
let buildLibraries =
    async {
        let! _ = deleteFiles generatedTestSources

        let mutable exitCode = 0

        for project in
            [
                "src/FsLexYacc.Runtime/FsLexYacc.Runtime.fsproj"
                "tests/JsonLexAndYaccExample/JsonLexAndYaccExample.fsproj"
                "tests/LexAndYaccMiniProject/LexAndYaccMiniProject.fsproj"
            ] do
            if exitCode = 0 then
                let! code = exec "dotnet" [ "build"; project; "-c"; "Release"; "/v:n" ]
                exitCode <- code

        return exitCode
    }

// --------------------------------------------------------------------------------------
// Packaging
// --------------------------------------------------------------------------------------

let pack =
    async {
        let releaseNotes = String.concat Environment.NewLine release.Notes

        // The per-project packages.
        let! projectPackages =
            exec
                "dotnet"
                [
                    "pack"
                    "FsLexYacc.slnx"
                    "-c"
                    "Release"
                    "-o"
                    "bin"
                    $"/p:PackageReleaseNotes={releaseNotes}"
                    $"/p:PackageVersion={release.NugetVersion}"
                ]

        if projectPackages <> 0 then
            return projectPackages
        else
            // The FsLexYacc meta-package, which is assembled by paket from a template rather
            // than from a project, because it ships the published tools instead of a library.
            return!
                exec
                    "dotnet"
                    [
                        "paket"
                        "pack"
                        "--template"
                        "nuget/FsLexYacc.template"
                        "--version"
                        release.NugetVersion
                        "--release-notes"
                        releaseNotes
                        "bin"
                    ]
    }

// --------------------------------------------------------------------------------------
// Pipelines
// --------------------------------------------------------------------------------------

/// Local tools first, because paket is one of them, then the paket restore that writes the
/// Paket.Restore.targets every project imports.
let restore =
    stage "Restore" {
        run "dotnet tool restore"
        run "dotnet paket restore"
    }

pipeline "Build" {
    workingDir root
    restore
    stage "Clean" { run (cleanDirs [ "bin"; "temp" ]) }
    stage "CheckFormat" { run "dotnet fantomas check ." }
    stage "AssemblyInfo" { run generateAssemblyInfo }
    stage "BuildTools" { run buildTools }
    stage "BuildLibraries" { run buildLibraries }
    stage "UnitTests" { run "dotnet test ." }
    stage "OldFsYaccTests" { run "dotnet fsi tests/fsyacc/OldFsYaccTests.fsx" }
    runIfOnlySpecified false
}

pipeline "Release" {
    workingDir root
    restore
    stage "Clean" { run (cleanDirs [ "bin"; "temp" ]) }
    stage "CheckFormat" { run "dotnet fantomas check ." }
    stage "AssemblyInfo" { run generateAssemblyInfo }
    stage "BuildTools" { run buildTools }
    stage "BuildLibraries" { run buildLibraries }
    stage "UnitTests" { run "dotnet test ." }
    stage "OldFsYaccTests" { run "dotnet fsi tests/fsyacc/OldFsYaccTests.fsx" }
    stage "NuGet" { run pack }
    runIfOnlySpecified true
}

pipeline "Docs" {
    workingDir root
    restore
    stage "CleanDocs" { run (cleanDirs [ "output"; ".fsdocs" ]) }
    stage "AssemblyInfo" { run generateAssemblyInfo }
    stage "BuildTools" { run buildTools }
    stage "BuildLibraries" { run buildLibraries }
    stage "GenerateDocs" { run "dotnet fsdocs build --eval" }
    runIfOnlySpecified true
}

tryPrintPipelineCommandHelp ()
