// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsLex")>]
[<assembly: AssemblyProductAttribute("FsLexYacc")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("7.0.5")>]
[<assembly: AssemblyFileVersionAttribute("7.0.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsLex"
    let [<Literal>] AssemblyProduct = "FsLexYacc"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "7.0.5"
    let [<Literal>] AssemblyFileVersion = "7.0.5"
