// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsLex")>]
[<assembly: AssemblyProductAttribute("FsLexYacc")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("9.0.1")>]
[<assembly: AssemblyFileVersionAttribute("9.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsLex"
    let [<Literal>] AssemblyProduct = "FsLexYacc"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "9.0.1"
    let [<Literal>] AssemblyFileVersion = "9.0.1"
