// Auto-Generated by build.fsx; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsYacc.Core")>]
[<assembly: AssemblyProductAttribute("FsLexYacc")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("12.0.0")>]
[<assembly: AssemblyFileVersionAttribute("12.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsYacc.Core"
    let [<Literal>] AssemblyProduct = "FsLexYacc"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "12.0.0"
    let [<Literal>] AssemblyFileVersion = "12.0.0"
