// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsLexYacc.Build.Tasks")>]
[<assembly: AssemblyProductAttribute("FsLexYacc.Build.Tasks")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("6.0.4")>]
[<assembly: AssemblyFileVersionAttribute("6.0.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsLexYacc.Build.Tasks"
    let [<Literal>] AssemblyProduct = "FsLexYacc.Build.Tasks"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "6.0.4"
    let [<Literal>] AssemblyFileVersion = "6.0.4"
