// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsYacc")>]
[<assembly: AssemblyProductAttribute("FsLexYacc")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("6.1.0")>]
[<assembly: AssemblyFileVersionAttribute("6.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsYacc"
    let [<Literal>] AssemblyProduct = "FsLexYacc"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "6.1.0"
    let [<Literal>] AssemblyFileVersion = "6.1.0"
