// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsLexYacc.Profile259")>]
[<assembly: AssemblyProductAttribute("FsLexYacc.Runtime")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("6.1.0")>]
[<assembly: AssemblyFileVersionAttribute("6.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsLexYacc.Profile259"
    let [<Literal>] AssemblyProduct = "FsLexYacc.Runtime"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "6.1.0"
    let [<Literal>] AssemblyFileVersion = "6.1.0"
