// Signature file for parser generated by fsyacc
module Parser
type token = 
  | OP_PLUS
  | OP_MINUS
  | OP_TIMES
  | OP_DIVIDE
  | LPAREN
  | RPAREN
  | EOF
  | INT of (int)
  | ID of (string)
type tokenId = 
    | TOKEN_OP_PLUS
    | TOKEN_OP_MINUS
    | TOKEN_OP_TIMES
    | TOKEN_OP_DIVIDE
    | TOKEN_LPAREN
    | TOKEN_RPAREN
    | TOKEN_EOF
    | TOKEN_INT
    | TOKEN_ID
    | TOKEN_end_of_input
    | TOKEN_error
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_Expr
/// This function maps tokens to integer indexes
val tagOfToken: token -> int

/// This function maps integer indexes to symbolic token ids
val tokenTagToTokenId: int -> tokenId

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
val prodIdxToNonTerminal: int -> nonTerminalId

/// This function gets the name of a token as a string
val token_to_string: token -> string
val start : (FSharp.Text.Lexing.LexBuffer<'cty> -> token) -> FSharp.Text.Lexing.LexBuffer<'cty> -> ( Syntax.Expr ) 
