// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsLexYacc.Runtime")>]
[<assembly: AssemblyProductAttribute("FsLexYacc.Runtime")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("11.0.1")>]
[<assembly: AssemblyFileVersionAttribute("11.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsLexYacc.Runtime"
    let [<Literal>] AssemblyProduct = "FsLexYacc.Runtime"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "11.0.1"
    let [<Literal>] AssemblyFileVersion = "11.0.1"
