// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsLexYacc.Runtime")>]
[<assembly: AssemblyProductAttribute("FsLexYacc.Runtime")>]
[<assembly: AssemblyDescriptionAttribute("FsLex/FsYacc lexer/parser generation tools")>]
[<assembly: AssemblyVersionAttribute("7.0.4")>]
[<assembly: AssemblyFileVersionAttribute("7.0.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsLexYacc.Runtime"
    let [<Literal>] AssemblyProduct = "FsLexYacc.Runtime"
    let [<Literal>] AssemblyDescription = "FsLex/FsYacc lexer/parser generation tools"
    let [<Literal>] AssemblyVersion = "7.0.4"
    let [<Literal>] AssemblyFileVersion = "7.0.4"
