name: Build and test

on:
  pull_request:
    branches:
    - master

permissions:
  contents: read
  security-events: write

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET for main project build
      uses: actions/setup-dotnet@v6
    - name: Install local tools
      run: dotnet tool restore
    - name: Paket restore
      run: dotnet paket restore
    - name: Build
      run: dotnet fsi build.fsx

  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
    - name: Install local tools
      run: dotnet tool restore
    - name: Paket restore
      run: dotnet paket restore
    - name: Analyze
      run: dotnet fsi build.fsx -p Analyze
      continue-on-error: true
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ./analysis.sarif
